import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";

const raleway = localFont({
    src: "./fonts/Raleway.woff2",
    variable: "--font-raleway",
    weight: "100 900",
});

export const metadata: Metadata = {
    title: "Comfort Foods",
    description: "Generated by create stathis mavridis",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en" className={raleway.variable}>
            <body className="antialiased">{children}</body>
        </html>
    );
}